### ISSUE TITLE
short size and long size in data layer

### ISSUE THREAD

**Issue by KevenLee** [zhaoweicai/cascade-rcnn#60]
Hi,
when I set long_size: 640, short_size:640 in train.prototxt, I got the following error:

F0930 05:59:31.305073 32644 detection_data_layer.cpp:197] Check failed: detection_data_param.long_size() > detection_data_param.short_size() (640 vs. 640) 

long_size should not be equal to short_size? why?

**Comment by zhaoweicai** [comment]
@KevenLee long_size is required to longer than short_size. If you want to specify fixed both sizes for the inputs, please specify ``resize_width`` and ``resize_height`` instead of ``short_size`` and ``long_size``. Please have a look at https://github.com/zhaoweicai/cascade-rcnn/blob/c4a1888552bd342d82b19234bd16f0b616524c95/src/caffe/layers/detection_data_layer.cpp#L178
